_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 15
  ATTENTION:
    CEM: True
    LOSS: True
    LOSS_WEIGHT: 0.7

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base1', )
  TEST: ('voc_2007_test_base1',)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (30000,50000)
  MAX_ITER: 70000  # 17.4 epochs
  CHECKPOINT_PERIOD: 50000
  WARMUP_ITERS: 100


TEST:
  EVAL_PERIOD: 20000

OUTPUT_DIR: "checkpoints/70000-base-CIR-fsdom"
