_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  # WEIGHTS: "checkpoints/s3-0.3-70000-CEM-minitrain.pth"
  WEIGHTS: "checkpoints/TFA_temp/s1-70000-base-CIR-fsodm.pth"
  # WEIGHTS: "checkpoints/s1-noloss-70000-CEM.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5
  ATTENTION:
    CEM: True
    LOSS: True
    LOSS_WEIGHT: 0.7
  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    # POST_NMS_TOPK_TRAIN: 2000
    NMS_THRESH: 0.8
    IOU_THRESHOLDS: [0.2,0.7]
    # PRE_NMS_TOPK_TRAIN: 4000
    # POST_NMS_TOPK_TRAIN: 4000
  # PROPOSAL_GENERATOR:
  #   FREEZE: True
  # RPN:
    # PRE_NMS_TOPK_TRAIN: 2000
    # POST_NMS_TOPK_TRAIN: 1000

  # ROI_HEADS:
  #   NUM_CLASSES: 20
  #   # OUTPUT_LAYER: "CosineSimOutputLayers"
  #   FREEZE_FEAT: False
  #   BATCH_SIZE_PER_IMAGE: 256
  #   IOU_THRESHOLDS: [0.4]
  ROI_HEADS:
    NUM_CLASSES: 20
    # OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
    # UNFREEZE_FC1: True
    UNFREEZE_FC2: True
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]

INPUT:
  CROP:
    ENABLED: TRUE
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800

DATASETS:
  TRAIN: ('voc_2007_trainval_all1_1shot',)
  TEST: ('voc_2007_test_all1',)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  GAMMA: 0.1
  STEPS: (100,200,300,400)
  MAX_ITER: 800
  CHECKPOINT_PERIOD: 50000
  WARMUP_ITERS: 10

TEST:
  EVAL_PERIOD: 50000

OUTPUT_DIR: "checkpoints/test"
