_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1-fsce-dior-lr005-ba4-28000-1/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
    # SCORE_THRESH_TEST: 0.0

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.5
      DECAY:
        ENABLED: True
        STEPS: [4000, 7000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  CROP:
    ENABLED: True

DATASETS:
  TRAIN: ('voc_2007_trainval_all1_5shot',)
  TEST: ('voc_2007_test_all1',)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.004
  GAMMA: 0.5
  STEPS: (100,200,300,400)
  MAX_ITER: 800
  CHECKPOINT_PERIOD: 200
  WARMUP_ITERS: 10

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 200

OUTPUT_DIR: "checkpoints/voc/5shot_CL_IoU-fsce-nwpu-lr001-ba1-1500-seed8"
